// <auto-generated />
namespace Lab3_LINQCodeFirst.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class create_insDept : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(create_insDept));
        
        string IMigrationMetadata.Id
        {
            get { return "202302132332217_create_insDept"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
